<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="41964" started-at="2020-05-10T19:19:04Z" finished-at="2020-05-10T19:19:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="41964" started-at="2020-05-10T19:19:04Z" finished-at="2020-05-10T19:19:46Z">
      <class name="com.wipro.Ass2.Ruthra_Olay_Germany">
        <test-method status="PASS" signature="startUp()[pri:0, instance:com.wipro.Ass2.Ruthra_Olay_Germany@1e4cb85]" name="startUp" is-config="true" duration-ms="11222" started-at="2020-05-11T00:48:53Z" finished-at="2020-05-11T00:49:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startUp -->
        <test-method status="FAIL" signature="olayGermany()[pri:0, instance:com.wipro.Ass2.Ruthra_Olay_Germany@1e4cb85]" name="olayGermany" duration-ms="41941" started-at="2020-05-11T00:49:04Z" finished-at="2020-05-11T00:49:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Registered is not sucessfully expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Registered is not sucessfully expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.wipro.Ass2.Ruthra_Olay_Germany.olayGermany(Ruthra_Olay_Germany.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- olayGermany -->
        <test-method status="PASS" signature="tearUP()[pri:0, instance:com.wipro.Ass2.Ruthra_Olay_Germany@1e4cb85]" name="tearUP" is-config="true" duration-ms="0" started-at="2020-05-11T00:49:46Z" finished-at="2020-05-11T00:49:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUP -->
      </class> <!-- com.wipro.Ass2.Ruthra_Olay_Germany -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
